Repository sourcegraph/handbook, pull requests merged in 2021-11, with the labels that each got.

#584 add AARRR experiment
  content/product/product_management/planning.md
Labels: handbook-announce

#607 add missing doc link to features data file
  data/features.yml
Labels: merge-on-any-approve

#627 Add validation for YAML data files
  .github/workflows/data-validation.yml
  .vscode/extensions.json
  content/editing/handbook-check-failures.md
  data/code_hosts.yml
  data/features.yml
  data/maturity_levels.yml
  data/product_areas.yml
  data/product_orgs.yml
  data/team.yml
  package.json
  schema/code_hosts.schema.json
  schema/features.schema.json
  schema/maturity_levels.schema.json
  schema/product_areas.schema.json
  schema/product_orgs.schema.json
  schema/team.schema.json
  src/scripts/check-links.mjs
  src/scripts/generated-pages.mjs
  yarn.lock
Labels: 🔧 Handbook tooling, handbook-announce

#111 Create people ops pm page
  content/people-ops/index.md
  content/people-ops/people-ops-project-management.md
Labels: stale

#593 How to triage issues with unclear owner
  .gitignore
  content/product/index.md
  content/product/product_management/responding_to_user_feedback.md
  data/product_areas.yml
  schema/product_areas.schema.json
  src/components/EditSection.tsx
  src/scripts/generated-pages.mjs
Labels: handbook-announce

#599 Correct feature data chart
  data/features.yml
Labels: merge-on-any-approve

#707 rename customer-driven value to customer-first, elaborate on it
  content/company/customer-first.md
  content/company/goals/2022_annual.md
  content/company/remote/remote_hackathons.md
  content/company/values.md
  content/engineering/career-development/framework.md
  content/engineering/core-application/onboarding/week-1.md
  content/marketing/content/editorial/blog_hackathon.md
  content/marketing/content/index.md
Labels: handbook-announce

#187 Updates to the social media handbook
  content/marketing/socialmedia.md
Labels: stale

#575 Clarify free pricing tier
  content/product/product_management/pricing.md
Labels: stale

#859 Removing Virginia from handbook support
  content/handbook/editing/index.md
Labels: handbook-announce

#854 create handbook content best practices page
  content/communication/content_guidelines/index.md
  content/handbook/editing/handbook-content-best-practices.md
  content/handbook/editing/index.md
  content/handbook/index.md
Labels: handbook-announce

#154 Implement internal link graph and backlinks
  src/lib/api.ts
  src/lib/getAllPages.ts
  src/lib/markdownToHtml.ts
  src/pages/[...slug].tsx
  src/pages/index.tsx
  src/pages/meta.tsx
Labels: 🏗 Handbook website, stale

#787 Clarify open source philosophy
  content/engineering/licenses.md
  content/product/product_management/pricing.md
Labels: handbook-announce

#889 devx: developer experience -> dev experience when referring to the team
  content/company/strategy/enablement/dev-experience/index.md
  content/engineering/distribution/index.md
  content/engineering/enablement/dev-experience/index.md
  content/engineering/incidents/playbooks/ci.md
  data/product_teams.yml
Labels: team/dev-experience

#820 Document product and engineering planning process
  content/company/goals/2021_q1.md
  content/company/strategy/index.md
  content/company/values.md
  content/engineering/engineering-management.md
  content/engineering/tracking_issues.md
  content/product-engineering/demo-day.md
  content/product-engineering/index.md
  content/product-engineering/planning-process.md
  content/product-engineering/strategy.md
  content/product-engineering/team.md
  content/product/index.md
  content/product/product_management/index.md
  content/product/product_management/planning.md
Labels: handbook-announce

#910 Updating managed instance config requests
  content/engineering/enablement/delivery/managed/creation_process.md
Labels: team/delivery

#926 Add note on separating documentation vs improvement tasks
  content/handbook/index.md
Labels: handbook-announce

#953 Restore large files check
  .github/workflows/large-files.yml
  src/scripts/check-large-files.ps1
Labels: 🔧 Handbook tooling

#924 Add more handbook-first guidance
  content/handbook/index.md
Labels: handbook-announce

#639 Update GraphQL Voyager instructions
  content/support/support-tools.md
Labels: stale

#1032 devx: prepare newsletter in handbook, add archive
  content/product-engineering/engineering/enablement/dev-experience/index.md
  content/product-engineering/engineering/enablement/dev-experience/newsletter.md
Labels: team/dev-experience

#841 Update active user events
  content/bizops/user_definitions.md
Labels: stale

#855 insights: added section about using github boards for project tracking instead of tracking issues
  content/product-engineering/engineering/code-graph/code-insights/processes.md
Labels: stale

#1042 Add value drivers
  content/marketing/index.md
  content/marketing/product-marketing/batch_changes_positioning.md
  content/marketing/value-drivers.md
Labels: handbook-announce
