Repository sourcegraph/handbook, pull requests merged in 2021-10, with the labels that each got.

#54 Better search styles
  src/styles/search.scss
Labels: 🏗 Handbook website

#58 Add labels to Renovate
  renovate.json
Labels: 🏗 Handbook website

#74 Add smartypants plugin
  content/communication/content_guidelines/style_and_mechanics.md
  package.json
  src/lib/markdownToHtml.ts
  src/lib/rehypeSmartypants.ts
  yarn.lock
Labels: 🏗 Handbook website

#59 Update readme to correct instructions
  README.md
  package.json
Labels: 🏗 Handbook website

#86 Document how to check links locally
  README.md
Labels: 🔧 Handbook tooling

#92 Write _redirects to out directory for Netlify
  package.json
  src/scripts/generate-redirects.mjs
Labels: 🏗 Handbook website

#97 Update .nvmrc
  .nvmrc
Labels: 🔧 Handbook tooling

#99 Fix timezone offset formatting
  src/lib/rehypeMarkupDates.ts
Labels: 🏗 Handbook website

#250 support: unified process for handling CCPA/GDPR data deletion requests; add checklist issue template
  content/ce/delete_users_guide.md
  content/ce/education.md
  content/support/index.md
  content/support/permanently_deleting_user_data.md
Labels: documentation
