Repository sourcegraph/handbook, pull requests merged in 2022-03, with the labels that each got.

#2597 Explicit requirements handling in SDLC
  content/departments/product-engineering/process/sdlc.md
Labels: soc2

#2386 Added link to computer standards for HDD
  content/departments/product-engineering/engineering/cloud/security/cryptography-policy.md
Labels: stale

#2379 Revert "took out the Team tier as it no longer exists"
  content/departments/product-engineering/product/process/pricing.md
Labels: stale

#2380 Revert "no longer has a team plan"
  content/departments/product-engineering/product/process/licensing.md
Labels: stale

#2625 Clarify that *all* use cases improve developer velocity
  content/strategy-goals/strategy/index.md
Labels: handbook-announce

#2456 Change Felix Kling reports_to to Loic
  data/team.yml
Labels: stale

#2664 Add Stephen's GitHub handle
  data/team.yml
Labels: merge-on-any-approve

#2660 Extend CSP
  content/departments/marketing/brand/brand_guidelines/color.md
  content/departments/marketing/brand/brand_guidelines/interactive-color-palette.js
  netlify.toml
Labels: merge-on-any-approve

#2377 Updated release process for vulnerabilities
  content/departments/product-engineering/engineering/cloud/security/index.md
Labels: stale

#2669 Add charter for #gender-diversity-allies cohort
  content/company-info-and-process/communication/code_of_conduct.md
  content/company-info-and-process/diversity-equity-and-inclusion/gender-diversity.md
  content/company-info-and-process/diversity-equity-and-inclusion/index.md
  content/company-info-and-process/diversity-equity-and-inclusion/personal-pronouns.md
  content/company-info-and-process/index.md
  content/company-info-and-process/values/index.md
  content/departments/people-ops/index.md
  content/index.md
Labels: handbook-announce

#2452 Delivery directors
  content/departments/product-engineering/engineering/cloud/delivery/delivery-directors.md
  content/departments/product-engineering/engineering/cloud/delivery/index.md
Labels: stale

#2690 Add mentorship program details
  content/company-info-and-process/index.md
  content/company-info-and-process/mentorship/index.md
  content/company-info-and-process/mentorship/operations.md
  content/index.md
Labels: handbook-announce

#2705 Adds descriptor to first line of signature
  content/company-info-and-process/communication/index.md
Labels: 📝 Handbook content

#2554 sdr manager interview process.md
  content/departments/sales/hiring/index.md
Labels: stale

#2717 Add more social channels
  content/company-info-and-process/communication/team_chat.md
Labels: 📝 Handbook content, handbook-announce

#2720 Add Thomas to team page
  data/team.yml
Labels: 📝 Handbook content

#2733 Add definition of technical acronyms
  data/glossary.yml
Labels: 📝 Handbook content

#2576 update fpt completed goals
  content/departments/product-engineering/engineering/enablement/frontend-platform/goals_completed.md
Labels: stale

#2754 Include release candidate build upgrade guide
  content/departments/product-engineering/engineering/cloud/delivery/managed/upgrade_process.md
Labels: team/delivery

#1334 Clarify remove user steps for sourcegraph.com
  content/departments/support/process/permanently_deleting_user_data.md
Labels: stale

#2788 Add productivity hack of connecting gcal to Zoom
  content/company-info-and-process/remote/teammate-recommended_productivity_hacks.md
Labels: merge-on-any-approve
