Repository sourcegraph/handbook, pull requests merged in 2022-12, with the labels that each got.

#5724 update v2 delete doc
  content/departments/cloud/technical-docs/v2.0/delete_process.md
Labels: merge-on-any-approve

#5754 Add changelog to design processes
  content/departments/engineering/design/design_process.md
Labels: handbook

#5757 Include priority and loe in support process
  content/departments/technical-success/support/process/support-workflow.md
Labels: stale
