Repository sourcegraph/handbook, pull requests merged in 2022-05, with the labels that each got.

#3220 Update blog post proposals to point to GitHub
  content/departments/marketing/content/editorial/editorial-process.md
Labels: 📝 Handbook content

#3309 Add names/roles of personas
  content/departments/marketing/process/personas.md
Labels: stale

#3383 Add 'Google Docs Quick Create' extension
  content/company-info-and-process/remote/teammate-recommended_productivity_hacks.md
Labels: stale

#3382 Add Justin Dorfman's Location
  content/team/locations.geojson
Labels: stale

#3316 update product gap opportunity guidance
  content/departments/product-engineering/product/process/surfacing_product_feedback.md
Labels: stale

#3420 bugfix/ MD date hover function
  src/lib/rehypeMarkupDates.ts
Labels: bug, team/content-platform
