Repository sourcegraph/handbook, pull requests merged in 2022-07, with the labels that each got.

#3948 Update v1.1 executors deployment guide
  content/departments/engineering/dev/admin-exp/devops/managed/v1.1/mi1-1_enable_executors_process.md
Labels: stale

#3996 Update celebration custom
  content/benefits-pay-perks/benefits-perks/celebrate.md
Labels: stale

#4227 Color palette min-width
  content/departments/engineering/design/brand_guidelines/color.md
Labels: team/content-platform, handbook

#4108 receipt policy on virtual card vendor payments
  content/departments/finance/process/payables.md
Labels: stale

#4126 Update marketing rapid response
  content/departments/marketing/marketing_rapid_response_process/index.md
Labels: stale

#4374 CPT and team updates
  content/departments/engineering/teams/content-platform/index.md
  data/team.yml
Labels: team/content-platform

#4387 Update GCP link for resize persistent disk
  content/departments/cloud/technical-docs/operations.md
Labels: documentation, team/devx

#4131 add design update per em-pm-pd discussion
  content/departments/engineering/teams/code-insights/processes.md
Labels: stale

#3966 Add links to key reports
  content/departments/bizops/data-analytics.md
Labels: stale

#4186 Update blog instructions to include Blog Post Starter Pack
  content/departments/marketing/blog.md
Labels: team/content-platform
