Repository sourcegraph/handbook, pull requests merged in 2022-01, with the labels that each got.

#717 How to report gating or license key issues
  content/departments/ce/process/license_keys.md
Labels: handbook-announce

#1473 Update Engineering Education and add TTPR metric
  content/strategy-goals/strategy/enablement/engineering-education/index.md
  content/strategy-goals/strategy/enablement/engineering-education/time-to-pull-request.md
Labels: stale

#1266 Add device usage privacy philosophy
  content/departments/tech-ops/process/team_device_usage_privacy.md
  content/index.md
Labels: stale

#1764 Fix career framework header
  src/lib/markdownToHtml.ts
  src/styles/content.scss
Labels: 🏗 Handbook website

#1333 create a new file for policies in company info
  content/company-info-and-process/policies/index.md
  content/index.md
Labels: stale

#1352 Vulnerability manegement policy
  content/departments/product-engineering/engineering/index.md
  content/departments/product-engineering/engineering/policies/index.md
  content/departments/product-engineering/engineering/policies/vulnerability-management-policy.md
Labels: stale

#1002 Add learnings section
  content/departments/marketing/content/editorial/editorial-strategy.md
Labels: 📝 Handbook content

#1651 SDR Team Recommended Reads
  content/departments/sales/sdrteam/Recommended Reads
  content/departments/sales/sdrteam/index.md
Labels: stale

#1870 Add product/engineering strategy to handbook
  content/departments/product-engineering/strategy-goals/index.md
Labels: handbook-announce

#1743 Update AWS information
  content/departments/product-engineering/engineering/cloud/security/infrastructure/playbooks.md
Labels: stale

#1997 Add docs to suspend and resume manage instances
  content/departments/product-engineering/engineering/cloud/delivery/managed/index.md
  content/departments/product-engineering/engineering/cloud/delivery/managed/operations.md
  content/departments/product-engineering/engineering/cloud/delivery/managed/resume_process.md
  content/departments/product-engineering/engineering/cloud/delivery/managed/suspend_process.md
Labels: team/delivery

#2037 Update Bio and issue creation links
  content/departments/product-engineering/engineering/enablement/content-platform/index.md
  data/team.yml
Labels: 📝 Handbook content

#2052 Remove white image background
  src/styles/content.scss
Labels: 🏗 Handbook website
