Repository sourcegraph/handbook, pull requests merged in 2022-04, with the labels that each got.

#2917 insights: add cloud amplitude dashboard to hb page
  content/departments/product-engineering/engineering/code-graph/code-insights/index.md
Labels: merge-on-any-approve

#2875 Updates to CPT documentation
  content/departments/product-engineering/engineering/enablement/content-platform/index.md
  data/product_teams.yml
  data/team.yml
Labels: documentation

#3056 Update Brand Colour Names
  content/departments/marketing/brand/brand_guidelines/color.md
Labels: team/content-platform

#2983 Initial skeleton of Datadog use cases
  content/departments/product-engineering/engineering/cloud/devops/datadog.md
  content/departments/product-engineering/engineering/cloud/devops/index.md
Labels: observability

#2933 Switched bizops reporting structure
  content/team/org_chart.md
Labels: stale

#2835 Removing extra words from index.md
  content/departments/support/tools/index.md
Labels: stale

#2840 Add missing link(s) to content/departments/product-engineering/process
  content/departments/product-engineering/process/index.md
Labels: stale

#3069 Add Victoria Fitoussi to team page
  data/team.yml
Labels: 📝 Handbook content
