Repository sourcegraph/handbook, pull requests merged in 2022-02, with the labels that each got.

#2002 Ship a first iteration of an SDLC (Soc2 GN-98)
  content/departments/product-engineering/index.md
  content/departments/product-engineering/process/index.md
  content/departments/product-engineering/process/sdlc.md
Labels: team/devx, soc2

#2132 remove handbook office hours
  content/handbook/index.md
Labels: handbook-announce

#2115 devx: document work leads process
  content/departments/product-engineering/engineering/enablement/dev-experience/index.md
Labels: team/devx

#2230 Add ping data removal to A/B test cleanup process
  content/departments/bizops/process/ab-testing.md
Labels: documentation

#2306 Update browser extension release process
  content/departments/product-engineering/engineering/cloud/growth-and-integrations/browser-extensions/release-process.md
Labels: merge-on-any-approve

#2082 repo-management: Add technical writing to learning resources
  content/departments/product-engineering/engineering/enablement/repo-management/learning-resources.md
Labels: stale

#2245 add using UTMs in product design
  content/departments/product-engineering/product/design/metrics/defining-metrics.md
Labels: stale

#2544 Refactor delivery team page
  content/departments/product-engineering/engineering/cloud/delivery/index.md
  content/departments/product-engineering/engineering/cloud/delivery/processes.md
Labels: team/delivery
