Repository sourcegraph/handbook, pull requests merged in 2023-07, with the labels that each got.

#7280 Add missing info about Go installation
  content/departments/engineering/dev/process/product_documentation.md
Labels: documentation, 📝 Handbook content, handbook

#7219 Update page title.md
  content/departments/people-talent/Required-posting-page.md
Labels: stale

#7339 Add instructions for external Cody contributors
  content/company-info-and-process/communication/rfcs/index.md
Labels: cody

#7330 Add steps on how to remove Support Agent from Slack
  content/departments/technical-success/support/process/foqal.md
Labels: stale

#7266 add internal docs for audit logs
  content/departments/cloud/technical-docs/audit-logs/index.md
Labels: stale

#7375 Update team_chat.md to prune reference to #announce-eng-updates
  content/company-info-and-process/communication/team_chat.md
Labels: stale
