Repository sourcegraph/handbook, pull requests merged in 2023-08, with the labels that each got.

#7540 Create page for CLAs (Contributor License Agreements)
  content/departments/engineering/dev/process/contributor-license-agreement.md
  content/departments/engineering/dev/process/index.md
Labels: 📝 Handbook content

#7504 Update index.md to drop enterprise from path
  content/departments/engineering/teams/cody/cody-gateway/index.md
Labels: stale

#7631 Add team member bio MB
  data/team.yml
Labels: teammate-onboarding

#7665 Update team.yml
  data/team.yml
Labels: 📝 Handbook content, handbook
